#!/bin/bash
set -e

app_dir=/var/django-app/

cmd_init() {
    if [ -z $1 ]; then
        echo "usage: app init appid"
        exit 1
    fi
    app_id=$1
    shift 1

    ssh-keygen -t rsa -N "" -C "Public key for app: $app_id" -f /root/.ssh/id_rsa > /dev/null
    echo $app_id > /APP_ID
    echo "Public paswrodless SSH-key for $app_id:"
    echo ""
    cat /root/.ssh/id_rsa.pub
    echo ""
}

cmd_pubkey() {
    cat /root/.ssh/id_rsa.pub
}


cmd_clone() {
    git clone "$@" $app_dir
}

cmd_manage() {
    cd $app_dir
    python manage.py "$@"
}

cmd_run() {
    wsgi_module=$1
    /usr/local/bin/uwsgi --http :8000 --chdir $app_dir --pp .. -w $wsgi_module
}

cmd=$1
shift 1
case $cmd in
    init|pull|manage|pubkey|run)
        cmd_$cmd "$@"
        ;;
    git|pip)
        cd $app_dir
        $cmd "$@"
        ;;
    *)
        echo "Nothing to do for $cmd"
        exit 1
        ;;
esac
